TRUTH = (
    "Acara TV apa yang paling kamu benci? Beri tahu alasannya!"
    "Kapan terakhir kali kamu berbohong?",
    "Kapan terakhir kali kamu menangis?",
"Kapan terakhir kali kamu kentut?",
"Apa ketakutan terbesarmu?",
"Apa fantasi terbesar atau terhanehmu?",
"Apa hal yang membuatmu senang orangtuamu tidak mengetahuinya?",
"Pernahkah kamu selingkuh?",
"Apa hal terburuk yang pernah kamu lakukan?",
"Apa rahasia yang tidak pernah kamu ceritakan kepada siapapun?",
"Apakah kamu punya bakat terpendam?",
"Siapa selebriti yang pertama kali bikin kamu naksir?",
"Apa pendapatmu tentang perselingkuhan?",
"Apa pengalaman intim terburuk yang pernah kamu alami?",
"Apakah kamu pernah melanggar hukum?",
"Apa hal paling memalukan yang pernah kamu lakukan? Kapan?,
"Apa hal yang paling membuatmu merasa insecure?",
"Kesalahan terburuk apa yang pernah kamu lakukan?",
"Apa hal paling menjijikkan yang pernah kamu lakukan?",
"Siapa orang yang paling ingin kamu cium di antara kita?",
"Hal terburuk apa yang pernah dilakukan orang terhadapmu?",
"Apa kebiasaan terburukmu?",
"Hal terburuk apa yang pernah kamu katakan/lakukan terhadap orang lain?",
"Apa penyesalan terburukmu?",
"Kenapa kamu putus dengan mantan yang sebelumnya?",
"Hal paling romantis apa yang pernah dilakukan orang lain buat kamu?",
"Apa yang pertama kali kamu pikirkan waktu pertama ketemu aku?",
"Kamu pernah stalk media sosial aku, enggak?",
"Kalau aku ada di samping kamu sekarang, apa yang bakal kamu lakukan?",
"Apa yang bikin kamu cemburu?",
"Apa yang bikin kamu bahagia banget?",
"Siapa gebetan kamu sekarang?",
"Kirim screenshot dari pencarian kamu di internet.",
"Coba salah satu dance challenge yang lagi viral.",
"Tulis namaku di badan kamu dan post fotonya di media sosial.",
"Kirim screenshot dari chat kamu.",
"Kasih tahu sesuatu yang kamu enggak pengin aku tahu.",
"Kasih tahu sesuatu yang kamu pengin aku tahu.",
"Aku tantang kamu jadi pacar selama satu hari penuh.",
"Post foto gebetan kamu di media sosial.",
  
)

DARE = (
    "Kalau kamu bisa jadi tidak terlihat, apa hal pertama yang akan kamu lakukan?"
    "siapa mantan yang paling kamu sayang?",
    "Apa rencana masa depanmu?",
    "Jika sebentar lagi kiamat, apa yg kamu lakukan ?",
"Kalo kamu disuruh operasi plastik dengan contoh wajah dari teman sekelasmu, wajah siapa yang akan kamu tiru?",
"Kamu pernah mencuri sesuatu gak?",
"Kamu takut mati? kenapa?",
"Kapan terakhir kali menangis dan mengapa?",
"kemampuan spesial kamu apa?",
"Kok bisa suka sama orang yang kamu sukai?",
"Pilih PACAR atau TEMAN ? berikan alasannya !",
"Quote apa yang paling kamu ingat dan kamu suka?",
"Rahasia apa yg belum pernah kamu katakan sampai ",
"Siapa nama mantan pacar teman mu yang pernah kamu sukai diam diam?",
"Siapa nama orang (beda gender) yang menurutmu akan asyik bila dijadikan pacar?",
"Siapa nama orang yang kamu benci, tapi kamu rasa orang itu suka sama kamu (nggak harus beda gender)?",
"Siapa nama orang yang pernah kamu ikutin diam-diam?",
"Siapa orang (lawan jenis) yang paling sering terlintas di pikiranmu?",
  
"Bagaimana perasaanmu jika sedang bersama denganku?",
"Seseorang seperti apa yang kamu inginkan?",
"Apa yang bikin kamu bahagia?",
"Apa yang bikin kamu cemburu?",
"siapa mantan yang paling kamu benci?",
"hal paling menjijikkan yang pernah kamu lakukan apa?",
"musik yang paling tidak kamu sukai?",
"hal memalukan bersama gebetan yang pernah terjadi?",
"siapa yang paling jelek diantara kita?",
"Apa rahasia yang kamu sembunyikan dari orangtuamu?",
"Siapa orang yang diam-diam kamu sukai?",
"Siapa orang terakhir yang kamu kepoin di media sosial?",
"Kalau ada jin yang memberikanmu tiga permohonan, apa yang kamu inginkan?",
"Siapa orang di antara kita yang menurutmu bisa lolos dari kiamat zombie dan siapa yang akan mati duluan? Beri tahu alasannya!",
"Apa tontonan favoritmu saat masih kecil?",
"Siapa orang yang paling sering kamu chat?",
"Apa kebohongan terbesar yang pernah kamu katakan kepada orangtuamu?",
"Apa mimpi paling aneh yang pernah kamu alami?",
"Ceritakan detail ciuman pertamamu…",
"Kapan terakhir kali kamu ngompol?",
"Menurutmu, hewan apa yang terlihat paling mirip denganmu?"
"Di antara kita, siapa orang yang paling kamu suka dalam konteks romantis?,
"Di antara kita, siapa orang yang menurutmu paling baik dan paling buruk sifatnya?",
)
