RUN_STRINGS = (
    "Now you see me, now you don't." "ε=ε=ε=ε=┌(;￣▽￣)┘",
    "Get back here!",
    "REEEEEEEEEEEEEEEEEE!!!!!!!",
    "Look out for the wall!",
    "Don't leave me alone with them!!",
    "You've got company!",
    "Chotto matte!",
    "Yare yare daze",
    "*Naruto run activated*",
    "*Nezuko run activated*",
    "Hey take responsibilty for what you just did!",
    "May the odds be ever in your favour.",
    "Run everyone, they just dropped a bomb 💣💣",
    "And they disappeared forever, never to be seen again.",
    "Legend has it, they're still running.",
    "Hasta la vista, baby.",
    "Ah, what a waste. I liked that one.",
    "As The Doctor would say... RUN!",
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_YONE_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

SLAP_TEMPLATES = (
    "{user1} menembak kepala {user2} dengan pistol",
    "{user1} mendorong {user2} ke jurang",
    "{user1} menyayat muka {user2} dengan pisau",
    "{user2} bunuh diri masuk ke jurang",
    "{user1} mendorong {user2} dari lantai 7",
    "{user1} menabrak {user2} dengan pesawat",
    "{user1} dan {user2} saling jatuh cinta",
    "{user1} membakar {user2}. Psikopat!",
    "{user1} dibunuh {user2} dengan pisau", 
    "{user1} melepas pakaian {user2}. Mau ngapain lu!",
    "{user1} dan {user2} tidur bersama. Maksiat gblk!",
    "{user1} jatuh cinta kepada {user2}.",
    "{user2} gantung diri di kamar mandi",
    "{user1} membunuh {user2} dari belakang!",
    "{user1} mendorong {user2} ke sungai",
    "{user1} membakar {user2} sampai hangus",
    "{user1} memakan tubuh {user2}. Kanibal!",
    "{user2} menabrakkan diri ke kereta.",
    "{user2} digergaji menjadi dua oleh {user1}.",
    "{user1} memcekik {user2} sampai mati",
    "{user2} diiris dan dipotong oleh {user1}.",
    "{user1} membunuh {user2} dengan kapal",
    "{user2} mati secara misterius",
    "{user1} menampar {user2} sampe berdarah!",
    "{user2} lari ketakutan melihat pocong",
    "{user1} melempar batu ke kepala {user2}",
    "{user1} melepas celana {user2}. Tobat gblk!",
    "{user1} menonjok muka {user2}",
    "{user1} melempar {user2} ke sumur.",
    "{user1} menonjok mata {user2}!",
    "{user1} menabrak {user2} dengan motor",
    "{user1} menampar {user2} dengan kayu",
    "{user1} melempar kursi ke {user2}",
    "{user1} menenggelamkan {user2} dilaut.",
    "{user1} menjahit bibir {user2}",
    "{user1} melindungi {user2} dari penjahat",
    "{user1} menandang {user2} sampai jatuh",
    "{user1} memotong kaki {user2} dengan kapak!",
    "{user1} mabuk bersama {user2} ",
    "{user1} mencium bibir {user2}.",
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
